# This is a basic workflow to help you get started with Actions

name: TestActions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test:
    name: Run the Test Job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
    fail-fast: false
    matrix:
      targetPlatform:
        - WebGL

    steps:
      - name: Notify deployment
        uses: 8398a7/action-slack@v3
        with:
          job_name: 'Run the Test Job (${{ matrix.targetPlatform }})'
          fields: job, took
          status: ${{ job.status }}
          author_name: わいわい「笑てたええねん」
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()